# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

# Mod properties
mod.version=0.3.19
mod.group=com.github.nagaresst
mod.id=nx-backup
mod.name=NX Backup
mod.author=NagaResst

# for fabric.mod.json
mod.mc_dep=[VERSIONED]
# for release title
mod.mc_title=[VERSIONED]
# for release metadata
mod.mc_targets=[VERSIONED]

# Loom version shared by fabric-loom-remap (<= 1.21.11) and fabric-loom (>= 26.1)
loomx.loom_version=1.17.19

# Global dependencies
deps.kotlin_loader_version=1.13.12+kotlin.2.4.0
deps.exposed_version=0.57.0
deps.fabric_loader=0.19.3
deps.ktor_version=2.3.12

# Versioned dependencies
deps.yarn_build=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.poly_lib=[VERSIONED]

# Publishing
publish.modrinth=wqsbtL6W
publish.curseforge=1153808
